### ISSUE TITLE
Signup Page / Input Component

### ISSUE THREAD

**Issue by chanw9503** [GiftWaveProjectTeam/GiftWave-FE#2]
## 기능 설명

Signup Page에 들어갈 input 컴포넌트에 대해서 만들 예정입니다.

Storybook Test 
1. 유효성 검사 후, 확인이 되면 초록색
2. 유효성 감사 후, 문제가 있으면 빨간색의 boarder값을 준다. 

Jest 진행 사항 (없을 시, 생략)

**Comment by 1nxeo** [comment]
공용 컴포넌트로 Input을 만들 예정인데 signup page에서 따로 input component를 만드는 이유가 있나요?
처음에는 `<input />`으로 사용하다가 이후 공용 컴포넌트 제작시 `<Input />`으로 교체하는 것으로 알고있었습니다.
어떻게 사용할 예정인지, 추후 어떻게 변경하실지에 대해서도 조금 더 구체적으로 설명해주시면 감사하겠습니다. #3 Button 컴포넌트도 마찬가지입니다.

**Comment by chanw9503** [comment]
안녕하세요. 인서님 글 남겨 주셔서 감사합니다. :) 

제가 계획한 내용은 현재 디자인이 나오지 않은 시점에서 
storybook을 활용한 기능 테스트를 먼저 진행하려고 합니다.

유효성 기능을 만든 다음에, hover이벤트에 대한 테스트를 진행하려고 하고,

추후에는 디자인이 나오는대로 현재 내용을 공용컴포넌트로 변경 후, 다시적용할 예정입니다.

#3 도 같은 맥락으로 이해해 주시면 될거같습니다.

이상입니다.

추가적으로 궁금한 사항있으시면 다시 연락주세요 :)
