### ISSUE TITLE
Post Page / FundInput Molecule

### ISSUE THREAD

**Issue by 1nxeo** [GiftWaveProjectTeam/GiftWave-FE#22]
1. 기능 설명
Post page에서 반복되는 컴포넌트인 입력항목들을 molecule로 만들었습니다.
이 과정에서 기존 atom - text 컴포넌트의 타입변경이 일부 있었습니다.

2. Storybook Test 진행 사항 (없을 시, 생략)
스토리북에서 테스트한 결과 비율까지 잘 나오는 것으로 확인됩니다.
스타일 변경이 필요한 부분 -> title 볼드처리

3. Jest 진행 사항 (없을 시, 생략)

4. 공유하고 싶은 내용
input의 종류가 많아서 이 부분을 어떻게 해야할지 모르겠습니다. 이 레이아웃만 Molecule로 만드는 것이 맞을까요?
구조상 label을 맨 바깥쪽에 감싸야하는데 이 때 Label atom 컴포넌트의 스타일링이 필요하지않습니다. 따라서 이 부분 같이 수정 필요할 것 같습니다.

**Comment by chanw9503** [comment]
Molecule 같은 경우, 재사용성이 있어야합니다. 
Molecule은 데이터를 표시하고 이벤트를 받을 수 있지만 "하나의 역할"만을 가지고, 재사용이 가능해야된다. 
이런 기준을 바탕으로 제작해주시면될거같고, 

label component에 수정이 필요할 경우, 수정후에 PR 이나 issue로 남겨주세용 :)
스타일링이 필요없다고 하시면, 옵셔널체이닝으로 타입지정을 해도 될거같네요
